### ISSUE TITLE
Special route for resources to return the count of a resource

### ISSUE THREAD

**Issue by emaxedon** [vinctustech/energize#10]
Let's say we have a resource `books` and we would like to display to the user the total number of books available.

This information could be retrieved maybe like the following:

```
GET http://localhost:8080/books/count HTTP/1.1
```

With the result:
```
data: 54
```

And for nested fields:
```
GET http://localhost:8080/books/authors/count HTTP/1.1
```

With the result:
```
data: 3
```

**Comment by edadma** [comment]
This was done already.

On Mar 27, 2017 13:26, "Edward W. Maxedon, Jr." <notifications@github.com>
wrote:

Assigned #10 <https://github.com/vinctustech/energize/issues/10> to @edadma
<https://github.com/edadma>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/vinctustech/energize/issues/10#event-1017015322>, or mute
the thread

**Comment by edadma** [comment]
It was done as
    get resource/size

**Comment by edadma** [comment]
Okay what I did doesn't work for nested fields. A new path segment matcher needs to be added for that.

**Comment by emaxedon** [comment]
Oops! That's why I didn't find it - I was searching the source for "count" and didn't see it. But yea the nested feature would be useful as well.
I'll add this to the docs now.
