### ISSUE TITLE
"order" query function not working

### ISSUE THREAD

**Issue by emaxedon** [vinctustech/energize#5]
Not sure if it's a bug - or I'm just not using it properly, but the `order` query function doesn't seem to work. So let's say I have a resource called `books` and I want to order by a book's `title` field.

```
GET http://localhost:8080/books?order=title
```

I think though the desired behaviour would be to use both a `sort` and `order` query function. So that one would specify the sort and whether it orders it either ascending or descending. If `order` is not specified, it would default to either ascending or descending.

```
GET http://localhost:8080/books?sort=title&order=asc
```

**Comment by edadma** [comment]
This is not a bug. Here is one of my original test examples when the feature was being coded. Against the `customers.energize` example do the following GET request

    GET http://localhost:8080/customers?order=City:asc,PostalCode:desc

Assuming that ID numbers are always chosen incrementally (as they are with H2), you can see that the double ordering has been performed correctly. Cities are in ascending order, and the two that are in Mexico D. F. (Mexico City) are ordered with their postal codes in descending order, but when you look at the ID numbers you can see that this would be the opposite of how a plain SELECT would have presented the data.

**Comment by edadma** [comment]
As to whether the ordering (ascending or descending) should be specified by a separate variable, we should do a thorough feature review before the 1.0 milestone to make sure every feature has been implemented the way most users would want it to be.  I favour the current approach because, as is demonstrated by this example, the ordering can be specified differently for each field.
